<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '- select status -' => '- Seleccionar status -',
    'Delete' => 'Borrar',
    'Done' => 'Hecho',
    'New' => 'Nuevo',
    'Order #{orderID}' => 'Pedido #{orderID}',
    'Orders' => 'Pedidos',
    'Products' => 'Productos',
    'Reset' => 'Limpiar',
    'Search' => 'Buscar',
    'Search Orders' => 'Buscar pedidos',
    'Set this order as done' => 'Marcar este pedido como hecho',
    'Set this order as new' => 'Marcar este pedido como nuevo',
];
