<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '- select category -' => '- Seleccionar Categoría -',
    '- select status -' => '- Seleccionar Status -',
    'Browse' => 'Buscador',
    'Create' => 'Crear',
    'Create Product' => 'Crear Producto',
    'Delete' => 'Borrar',
    'If empty it will be generated from name' => 'Si Está Vacío, Se Generará Con Nombre',
    'Products' => 'Productos',
    'Reset' => 'Limpiar',
    'Save' => 'Guardar',
    'Search' => 'Buscar',
    'Search Products' => 'Buscar Productos',
    'Update' => 'Actualizar',
    'Update product: ' => 'Actualizar Productos: ',
    'View on site' => 'Ver En Línea',
];
