<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Cart' => 'Carrito',
    'Category' => 'Categoría',
    'Clear Cart' => 'Vaciar Carrito',
    'Continue shopping' => 'Continuar Comprando',
    'Count of products' => 'Número De Productos',
    'Image' => 'Imagen',
    'It can bu used when you are contact us to know some information about your order' => 'Esto Se Puede Utilizar Para Obtener Información Sobre Pedidos',
    'Order' => 'Pedido',
    'Ordered successful' => 'Pedido Realizado Correctamente',
    'Price' => 'Precio',
    'Product' => 'Producto',
    'Reset' => 'Limpiar',
    'Summary' => 'Resumen',
    'Total cost' => 'Coste Total',
    'Your order number: {orderNumber}' => 'Tu Número De Pedido: {orderNumber}',
    'Your request was successfully ordered. We will contact you soon' => 'Su Pedido Se Ha Emitido Correctamente. Nos Pondremos En Contacto Con Usted',
];
